### ISSUE TITLE
Not working on Gnome 3.34

### ISSUE THREAD

**Issue by raushankumar27** [iamlemec/miniview#12]
Not working on Gnome 3.34

**Comment by iamlemec** [comment]
Thanks for the info! Tracking down the issues now.

**Comment by iamlemec** [comment]
Ok, found the issue. We should be doing `this._windowClone.set_source(win)` instead of `this._windowClone.set_source(win.get_texture())`. Honestly, I'm not sure what changes necessitated this, but it works. In fact, it seems to backwards compatible with at least 3.32.

I'll commit here now. If anyone out there can test this, would be much appreciated.

**Comment by raushankumar27** [comment]
its working after changes in gnome 3.34
